import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*.{ts,tsx,mts,js,jsx,mjs}": [
      "vp fmt --no-error-on-unmatched-pattern",
      "biome lint --only=noUnusedImports --fix",
      "vp lint --threads=2 --type-aware --type-check --quiet",
      "biome check --diagnostic-level=error --no-errors-on-unmatched",
    ],
  },
  lint: {
    options: {
      typeAware: true,
      typeCheck: true,
    },
    plugins: [
      "unicorn",
      "typescript",
      "oxc",
      "import",
      "eslint",
      "react",
      "react-perf",
      "vitest",
      "promise",
      "jest",
      "jsx-a11y",
    ],
    categories: {},
    env: {
      builtin: true,
      browser: true,
    },
    globals: {
      Buffer: "readonly",
      clearImmediate: "readonly",
      global: "readonly",
      process: "readonly",
      setImmediate: "readonly",
      BuildError: "readonly",
      BuildMessage: "readonly",
      Bun: "readonly",
      HTMLRewriter: "readonly",
      Loader: "readonly",
      ResolveError: "readonly",
      ResolveMessage: "readonly",
      ShadowRealm: "readonly",
      __dirname: "readonly",
      module: "readonly",
      require: "readonly",
    },
    settings: {
      "jsx-a11y": {
        components: {},
        attributes: {},
      },
      next: {
        rootDir: [],
      },
      react: {
        formComponents: [],
        linkComponents: [],
        version: "19.0.0",
      },
      jsdoc: {
        ignorePrivate: false,
        ignoreInternal: false,
        ignoreReplacesDocs: true,
        overrideReplacesDocs: true,
        augmentsExtendsReplacesDocs: false,
        implementsReplacesDocs: false,
        exemptDestructuredRootsFromChecks: false,
        tagNamePreference: {},
      },
      vitest: {
        typecheck: false,
      },
    },
    ignorePatterns: [
      "bun.lock",
      "routeTree.gen.ts",
      "**/openapi/clients",
      "**/openapi/client-tests",
      ".agents",
      ".output",
      "**/.agents/**",
      "**/.next/**",
      "**/.output/**",
      "**/.turbo/**",
      "**/dist/**",
      "**/generated/**",
      "**/node_modules/**",
      "**/openapi/client-tests/**",
      "**/openapi/clients/**",
      "**/out/**",
      "**/temp/**",
      "**/*.lock",
      "**/routeTree.gen.ts",
      "eslint.config.ts",
      "eslint.config.mjs",
    ],
    rules: {
      "import/no-cycle": "error",
      "for-direction": "warn",
      "no-async-promise-executor": "warn",
      "no-caller": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-console": "warn",
      "no-const-assign": "warn",
      "no-constant-binary-expression": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-delete-var": "warn",
      "no-dupe-class-members": "off",
      "no-dupe-else-if": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-empty-static-block": "warn",
      "no-eval": "warn",
      "no-ex-assign": "warn",
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-loss-of-precision": "off",
      "no-new-native-nonconstructor": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-self-assign": "warn",
      "no-setter-return": "warn",
      "no-shadow-restricted-names": "warn",
      "no-sparse-arrays": "warn",
      "no-this-before-super": "warn",
      "no-unassigned-vars": "warn",
      "no-unsafe-finally": "warn",
      "no-unsafe-negation": "warn",
      "no-unsafe-optional-chaining": "warn",
      "no-unused-expressions": "error",
      "no-unused-labels": "warn",
      "no-unused-private-class-members": "warn",
      "no-unused-vars": "error",
      "no-useless-backreference": "warn",
      "no-useless-catch": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-with": "warn",
      "require-yield": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",
      "eslint/require-await": "warn",
      "oxc/bad-array-method-on-arguments": "warn",
      "oxc/bad-char-at-comparison": "warn",
      "oxc/bad-comparison-sequence": "warn",
      "oxc/bad-min-max-func": "warn",
      "oxc/bad-object-literal-comparison": "warn",
      "oxc/bad-replace-all-arg": "warn",
      "oxc/const-comparisons": "warn",
      "oxc/double-comparisons": "warn",
      "oxc/erasing-op": "warn",
      "oxc/missing-throw": "warn",
      "oxc/number-arg-out-of-range": "warn",
      "oxc/only-used-in-recursion": "warn",
      "oxc/uninvoked-array-callback": "warn",
      "promise/prefer-await-to-then": "error",
      "typescript/await-thenable": "warn",
      "typescript/no-array-delete": "warn",
      "typescript/no-base-to-string": "warn",
      "typescript/no-duplicate-enum-values": "warn",
      "typescript/no-duplicate-type-constituents": "warn",
      "typescript/no-extra-non-null-assertion": "warn",
      "typescript/no-floating-promises": "warn",
      "typescript/no-for-in-array": "warn",
      "typescript/no-implied-eval": "warn",
      "typescript/no-meaningless-void-operator": "warn",
      "typescript/no-misused-new": "warn",
      "typescript/no-misused-spread": "warn",
      "typescript/no-non-null-asserted-optional-chain": "warn",
      "typescript/no-redundant-type-constituents": "warn",
      "typescript/no-this-alias": "warn",
      "typescript/no-unnecessary-parameter-property-assignment": "warn",
      "typescript/no-unsafe-declaration-merging": "warn",
      "typescript/no-unsafe-unary-minus": "warn",
      "typescript/no-useless-empty-export": "warn",
      "typescript/no-wrapper-object-types": "warn",
      "typescript/prefer-as-const": "warn",
      "typescript/require-array-sort-compare": "warn",
      "typescript/restrict-template-expressions": "warn",
      "typescript/triple-slash-reference": "warn",
      "typescript/unbound-method": "warn",
      "unicorn/no-await-in-promise-methods": "warn",
      "unicorn/no-empty-file": "warn",
      "unicorn/no-invalid-fetch-options": "warn",
      "unicorn/no-invalid-remove-event-listener": "warn",
      "unicorn/no-new-array": "warn",
      "unicorn/no-single-promise-in-promise-methods": "warn",
      "unicorn/no-thenable": "warn",
      "unicorn/no-unnecessary-await": "warn",
      "unicorn/no-useless-fallback-in-spread": "warn",
      "unicorn/no-useless-length-check": "warn",
      "unicorn/no-useless-spread": "warn",
      "unicorn/prefer-set-size": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      "no-array-constructor": "error",
      "no-useless-constructor": "error",
      "constructor-super": "error",
      "getter-return": "error",
      "no-case-declarations": "error",
      "no-empty": "error",
      "no-fallthrough": "error",
      "no-misleading-character-class": "error",
      "no-prototype-builtins": "error",
      "no-regex-spaces": "error",
      "no-undef": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "preserve-caught-error": "error",
      "react/display-name": "error",
      "react/jsx-key": "error",
      "react/jsx-no-comment-textnodes": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-target-blank": "error",
      "react/jsx-no-undef": "error",
      "react/no-children-prop": "error",
      "react/no-danger-with-children": "error",
      "react/no-direct-mutation-state": "error",
      "react/no-find-dom-node": "error",
      "react/no-is-mounted": "error",
      "react/no-render-return-value": "error",
      "react/no-string-refs": "error",
      "react/no-unescaped-entities": "error",
      "react/no-unknown-property": "error",
      "react/no-unsafe": "off",
      "react/require-render-return": "error",
      "unicorn/no-array-for-each": "warn",
      "unicorn/prefer-includes": "warn",
      "unicorn/prefer-logical-operator-over-ternary": "warn",
      "promise/always-return": "error",
      "promise/no-return-wrap": "error",
      "promise/param-names": "error",
      "promise/catch-or-return": "error",
      "promise/no-nesting": "warn",
      "promise/no-promise-in-callback": "warn",
      "promise/no-callback-in-promise": "warn",
      "promise/no-new-statics": "error",
      "promise/no-return-in-finally": "warn",
      "promise/valid-params": "warn",
      "jest/no-export": "off",
      "jest/no-focused-tests": "off",
      "jsx-a11y/alt-text": "off",
      "jsx-a11y/anchor-has-content": "off",
      "jsx-a11y/anchor-is-valid": "off",
      "jsx-a11y/aria-activedescendant-has-tabindex": "off",
      "jsx-a11y/aria-props": "off",
      "jsx-a11y/aria-proptypes": "off",
      "jsx-a11y/aria-role": "off",
      "jsx-a11y/aria-unsupported-elements": "off",
      "jsx-a11y/autocomplete-valid": "off",
      "jsx-a11y/click-events-have-key-events": "off",
      "jsx-a11y/heading-has-content": "off",
      "jsx-a11y/html-has-lang": "off",
      "jsx-a11y/iframe-has-title": "off",
      "jsx-a11y/img-redundant-alt": "off",
      "jsx-a11y/label-has-associated-control": "off",
      "jsx-a11y/lang": "off",
      "jsx-a11y/media-has-caption": "off",
      "jsx-a11y/mouse-events-have-key-events": "off",
      "jsx-a11y/no-access-key": "off",
      "jsx-a11y/no-aria-hidden-on-focusable": "off",
      "jsx-a11y/no-autofocus": "off",
      "jsx-a11y/no-distracting-elements": "off",
      "jsx-a11y/no-noninteractive-tabindex": "off",
      "jsx-a11y/no-redundant-roles": "off",
      "jsx-a11y/no-static-element-interactions": "off",
      "jsx-a11y/prefer-tag-over-role": "off",
      "jsx-a11y/role-has-required-aria-props": "off",
      "jsx-a11y/role-supports-aria-props": "off",
      "jsx-a11y/scope": "off",
      "jsx-a11y/tabindex-no-positive": "off",
      "react/void-dom-elements-no-children": "off",
      "react/react-in-jsx-scope": "off",
    },
    overrides: [
      {
        files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-var": "error",
          "no-with": "off",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
    ],
  },
  fmt: {
    trailingComma: "es5",
    experimentalSortImports: {
      groups: [
        ["unknown"],
        ["builtin"],
        ["external"],
        ["internal"],
        ["parent"],
        ["sibling"],
        ["index"],
      ],
    },
    experimentalTailwindcss: {
      attributes: ["class", "className"],
      functions: ["twMerge", "cn", "clsx"],
      preserveDuplicates: false,
      preserveWhitespace: false,
    },
    experimentalSortPackageJson: {
      sortScripts: true,
    },
    ignorePatterns: [
      "bun.lock",
      "routeTree.gen.ts",
      "**/openapi/clients",
      "**/openapi/client-tests",
      ".agents",
      ".output",
      ".gerrit_version.json",
    ],
  },
});
